# Generated by Django 4.0.2 on 2022-03-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='access',
            new_name='access_token',
        ),
    ]
